In [1]:
import numpy as np

In [2]:
M = np.asanyarray([[1,2],[2,1],[3,4],[4,3]])

In [3]:
u,sigma, v = np.linalg.svd(M, full_matrices = False)

In [4]:
u

array([[-0.27854301,  0.5       ],
       [-0.27854301, -0.5       ],
       [-0.64993368,  0.5       ],
       [-0.64993368, -0.5       ]])

In [5]:
sigma

array([7.61577311, 1.41421356])

In [6]:
v

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [7]:
np.dot(np.dot(u,np.diag(sigma)), v)

array([[1., 2.],
       [2., 1.],
       [3., 4.],
       [4., 3.]])

In [20]:
Evals, Evecs  = np.linalg.eigh(np.dot(M.T,M))

In [21]:
idx = Evals.argsort()[::-1]   
Evals = Evals[idx]
Evecs = Evecs[:,idx]
idx

array([1, 0])

In [22]:
Evals

array([58.,  2.])

In [23]:
Evecs

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])